using HandlingAdvancedExceptions;



try
{
	AdvancedEx.FirstException();

}
catch (Exception ex)
{

    Console.WriteLine(ex);
}

